language: node_js
node_js:
- "9"

# Only build tags
if: tag IS present

jobs:
  include:
    - stage: "Lint"
      name: "Linting"
      script:  npm run lint
    - stage: test
      name: "Testing"
    - name: "Unit test"
      script:  npm run unit
    - name: "Integration Test"
      script:  npm run integration
    - name: "Unit and integration synchronisation test test"
      script:  npm run InSync
    - stage: npm publish
      name: "Publish to npm registry"
      script: skip
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $EMAIL
        skip_cleanup: true
        on:
          branch: master
          tags: true

notifications:
  email:
    recipients:
    - $EMAIL
    on_success: change
    on_failure: always