language: node_js
node_js:
- "9"

jobs:
  include:
    - stage: "Lint"
      name: "Linting"
      script:  npm run lint
    - stage: test
      name: "Testing"
    - name: "Unit test"
      script:  npm run cover unit
    - name: "Integration Test"
      script:  npm run cover integration
    - name: "Unit and integration synchronisation test test"
      script:  npm run cover InSync
    - stage: build
      name: "Building"
      script:  npm run build
    - stage: npm publish
      name: "Publish to npm registry"
      script: skip
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $EMAIL
        on:
          branch: master
          tags: true

notifications:
  email:
    recipients:
    - Skitionek@gmail.com
    on_success: change
    on_failure: always