language: node_js
node_js:
- "9"

jobs:
  include:
    - stage: update
      if: type = cron
    - name: "Update packages"
      script: npm run update:packages
    - name: "Commit update"
      script: git commit -am "update dependencies"
    - name: "Patch version number"
      script: npm version patch -m "update dependencies"
    - name: "Push update to git"
      script: git push --tags
    - stage: "Linting"
      script:  npm run lint
    - stage: test
    - name: "Unit test"
      script:  npm run cover unit
    - name: "Integration Test"
      script:  npm run cover integration
    - name: "Unit and integration synchronisation test test"
      script:  npm run cover InSync
    - stage: build
      script:  npm run build
    - stage: npm publish
      script: skip
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $EMAIL
        on:
          branch: master
          tags: true

after_success:
- ./patch.sh

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - Skitionek@gmail.com
    on_success: change
    on_failure: always